### ISSUE TITLE
Change default setup and create a list of maps

### ISSUE THREAD

**Issue by MySelfLuls** [splewis/csgo-pug-setup#115]
So this is combined into one because it's not really anything long.
I'd like to know if its possible to change the default setup to something specific, and just make it auto-load on the server.

Is there also a way to make a maplist? So after a match it auto-loads into the other map I have specified, this should be easily changeable.
I'd like something they use in the competitive servers, this is for example the way they veto and make picks.

This is for BO3

1. Team A will veto the first map
2. Team B will veto the second map
3. Team A will pick the first map
4. Team B will pick the second map
5. Team A will veto the third map
6. Team B will veto the forth map
7. The last map in the pool is the deciding map 

So when the team picks a map, that means they also decide which side to start on.

This is for BO5

1. Team A will veto the first map
2. Team B will veto the second map
3. Team A will pick the first map
4. Team B will pick the second map
5. Team A will pick the third map
6. Team B will pick the forth map
7. The last map in the pool is the deciding map

**Comment by BarclayTech** [comment]
It's something that's perfectly possible, though not in the plugin atm.

Warmod already does this, maybe for now that's a better plugin for you.

Something I'm seeing more with this plugin is that it's straying away from it's original basic design, which isn't necessarily a bad thing, it just shows that this plugin is more what people want.

I hope splewis does start to expand in the plugins basic functions further, I know knife rounds weren't an original part of the plugin. You can still "keep it simple Splewis". But also take in mind that people request these changes because they enjoy this plugin more than others, me included.

**Comment by splewis** [comment]
You can have it "autoload" with ``sm_pugsetup_autosetup 1``, where it will use the default setup settings.

The problem with a full fledged veto system + map changes is storing so much game state across maps. I always made the plugin have a laissez faire approach to what it actually did so the CS:GO itself was doing most the work unaffacted - adding more map management/player management/etc. conflicts with that. I'm not sure that it's worth the effort to add those things here when warmod already does it pretty well.

**Comment by MySelfLuls** [comment]
But is it possible to change the default setup settings?

You already have a veto system, it would be implementing a pick system into the veto. I just believe this plugin can do more, or at least have the possibilities to do more.

**Comment by splewis** [comment]
https://github.com/splewis/csgo-pug-setup#configuration

https://github.com/splewis/csgo-pug-setup/blob/master/configs/pugsetup/setupoptions.cfg

Of course it can, but I'm probably not going to add it myself.
