### ISSUE TITLE
How RWS calculated ? 

### ISSUE THREAD

**Issue by nguyenbaodanh** [splewis/csgo-pug-setup#147]
How RWS calculated ? 
I don't see any SQL / database related here , so how RWS of each players saved  and calculated to balance every matches  ?

**Comment by JustinDanielson** [comment]
On esea? RWS is your percentage of total damage on the round out of 500. If
the bomb is planted or defused then it is out of 550. You get 0 rws for
losing a round. Imo rws is flawed because they don't give much credit for
doing the objective. It could be 525 if you plant and win by eliminating
all enemies and then 575 or 600 for defuse or explosion.

**Comment by splewis** [comment]
It's mostly an implementation detail. I'd recommend reading the source code since it's not very complex: https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup_rwsbalancer.sp

It assigns points for each action, and a player's rws each round is (their points) / (sum of their teams points) if they won the round, or 0 if they lost. That plugin saves using clientprefs cookies right now, which uses a sqlite db by default in sourcemod.
