### ISSUE TITLE
quick start

### ISSUE THREAD

**Issue by sam0324sam** [splewis/csgo-pug-setup#151]
### Expected behavior
i want quick start into knife round like faceit,but I just find quick start setting with knife to live.
please help~

### Actual behavior
no setting

### Steps to reproduce
- Plugin version:  newest
- Sourcemod version: newest

**Comment by splewis** [comment]
I don't understand what "quick start" means.

If you mean a way to not have players .ready up, then this plugin won't meet your needs.

**Comment by sam0324sam** [comment]
oh sorry my bad English.
that is just restart 1 time  to starting knife , like face it,not 3 times,can plugin do it?
thanks reply!

**Comment by splewis** [comment]
``sm_pugsetup_quick_restarts 1`` will skip the live-on-3 restart.

For aim maps; the plugin has nothing to do with how clients will download maps. It just runs a ``changelevel <map>`` command in console. If the server is changing to a workshop map, it'll be a workshop download. Otherwise it will download from the server or a sv_downloadurl like usual.

**Comment by sam0324sam** [comment]
thank you very much!
