### ISSUE TITLE
Captain picking order

### ISSUE THREAD

**Issue by spacecow123** [splewis/csgo-pug-setup#170]
Is it possible to add a 3rd order of picking teams? ABBABABA?

Thanks for making this mod BTW it is amazing for my group of friends 10 mans.

**Comment by splewis** [comment]
There is a cvar  ``sm_pugsetup_snake_captain_picks`` with description ``Whether captains will pick players in a "snaked" fashion rather than alternating, e.g. ABBAABBA rather than ABABABAB``.

So right now, you can't do that. I'm be fine with a 3rd setting for this cvar where if you set it to 2, then the ABBABABA order is used.

**Comment by luckykev** [comment]
Were you planning on implementing this, @splewis? Have a '2' option that sets team picks to ABBABABA?
