### ISSUE TITLE
live config chooser

### ISSUE THREAD

**Issue by superbroleon** [splewis/csgo-pug-setup#188]
So i want to request a well needed feature i think which is an option to to change the live config in the .setup menu. There was a feature like this 2 years ago with different map groups aswell but i think that is not as important.

**Comment by splewis** [comment]
There was never part of pugsetup, but I left my attempt at doing it on the [feature-config-choosing](https://github.com/splewis/csgo-pug-setup/commit/674af196d152ae6cc9992912b7790978135e7a33) branch.

I never finished it because there was a bug and it didn't work, and never went back to try and fix it.

**Comment by superbroleon** [comment]
So are you gonna try it again? Because i think that feature is pretty necessary, if you wan't to play like 3v3 or 2v2 not on a defuse map but on an aim map. I probably dont have to much no-how but i'd like to help nonethelsess if there is anything i can do...? If you are busy with other stuff or smth..
Anyway nice addon overall. 👍

**Comment by Technoblazed** [comment]
The branch is so outdated it would need doing from scratch, doesn't look like it would be /that/ hard to do, I'll see if I get the time at some point.

**Comment by splewis** [comment]
I don't think I'm ever going to implement this.
