### ISSUE TITLE
Overtime

### ISSUE THREAD

**Issue by SuplenC** [splewis/csgo-pug-setup#228]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Overtime should be played out, 

### Actual behavior
The game ends at one team winning

### Steps to reproduce
- Plugin version: Last
- Sourcemod version: Last
- Steps to reproduce (please be specific): At 15-15 it should be played out.

I do have overtime commands set up in the live.cfg file

Also asking another question about "playout" command I found in the setupoptions.cfg but without explanation.

**Comment by Technoblazed** [comment]
1) "Last" isn't a version.
2) Can you upload your live.cfg and pastebin it here.
3) "Playout" plays all rounds, mostly for scrims, if you have overtime enabled with this the game will never end.

**Comment by SuplenC** [comment]
1. SourceMod: 1.9 6247 Build, mod: 2.0.4
2. https://pastebin.com/8bM48LAG
3. Ok good to know as I use it for PCW. Thanks.

**Comment by splewis** [comment]
If you enable the playout option mp_overtime_enable is automatically disabled: https://github.com/splewis/csgo-pug-setup/blob/master/scripting/pugsetup.sp#L1914

That's because when you set ``mp_match_can_clinch 0`` and ``mp_overtime_enable 1``, the server will automatically start OT after 30 rounds regardless of the score (the score could be 30-0, it would still start OT).

That's why OT is disabled in that case. Playing out maxrounds is typically only done in practice, and playing OT in that context doesn't really make sense.
