### ISSUE TITLE
Cannot ready up after new CSGO update

### ISSUE THREAD

**Issue by spacecow123** [splewis/csgo-pug-setup#232]
If reporting a bug, fill in the following sections:

### Expected behavior
ready dialogue shows up after typing !setup in chat.

### Actual behavior
![pug](https://user-images.githubusercontent.com/26336759/44185799-4fafbf80-a0db-11e8-88a9-b2180fb93d37.PNG) Errors show up in console

Serve changes to warmup map but players cannot ready up.

### Steps to reproduce
- Plugin version: 2.0.4
- Sourcemod version:1.9
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
I just added this FAQ entry:

https://github.com/splewis/csgo-pug-setup/wiki/Frequently-Asked-Questions#gamedata-issues-aka-help-a-csgo-update-broke-the-mod

Does that answer your question? (I ask because I intended to start posting that link only when faced with similar questions, as this comes up often)

**Comment by spacecow123** [comment]
Thanks for the fast response. that worked!
