### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by xMaZax** [splewis/csgo-pug-setup#278]
when there is a game 5 on 5 team, and if the administrator is sitting in the spectators after the knife round as the teams change places in .swap or .stay the server! (if no one in the spectators it is not krašit server)

**Comment by borzaka** [comment]
Need more info to investigate it.
Don't just delete the issue template, fill out, because it helps to identify the problem.

We need to know:
- Plugin version
- Sourcemod version
- What other plugins are used
- steps to reproduce
- crash logs

My first guess is that you are using some other plugin(s) which interfere with pug-setup.

**Comment by splewis** [comment]
If you can provide the above info feel free to reopen this.

Otherwise there's not enough information here to do anything.
