### ISSUE TITLE
lag issue during demo recording and request to add feature

### ISSUE THREAD

**Issue by Sarthak001** [splewis/csgo-pug-setup#349]
i need answers to 2-3 questions and need a new feature. if u guys add this features to the plugin i will be grateful.
i am currently running my servers on 2Gb ram and 1vcpu@2.8 GHz - 3.2 GHz.
1. does the above specs sufficient to run a 128 tick csgo scrim.
2. does recording demos using the feature put stress on server?(when demos recording is on the sometimes player screen freeze for split second and then the player lags for 1-2 sec.

#features(that i hope will be added in the future updates)

1. can u make a cvar that determine how many pauses a team can take during the match.
(mp_team_timeout_max "n" and mp_team_timeout_time "30") and admins can pause/unpause match unlimited numbers of time.

thank you

**Comment by kratos1812** [comment]
Hello, your spect are low. As far as I know 2 Gb Ram is not enough to use gotv, try upgrating it to 8 gb ram. Also, your Cpu Freq is a litte bit low, csgo uses only 1 core, the most important part is the cpu freq. For better results you cango with 3,8 - 4,2

I would love the tose see the feature too btw

**Comment by splewis** [comment]
> I am trying to add this as an adaptive feature, so the demorec end is either the 4 seconds it is now or tv_delay if that is longer (could also be a config option), because the lag to GOTV is apparent and spoils the end of the game most of the time.

I was under the impression this issue was fixed in CS:GO itself over a year ago, but if not - adding a `tv_delay + buffer` instead of the fixed [4 seconds](https://github.com/splewis/csgo-pug-setup/blob/6d5077044c5fad94faa3bf03ccac3117a9591500/scripting/pugsetup.sp#L1951) sounds good to me.

As for the rest of of this: I don't know what server specs work. That's unrelated to pugsetup. 

For pausing: I don't intend to add additional paus settings to this plugin. It's not intended for competitive play, and there's already a builtin pausing system with those exact cvars you mention, so I'm not sure that's any value in replicating that.
