### ISSUE TITLE
BO2 Bo3 maps not changing

### ISSUE THREAD

**Issue by tornike015** [splewis/csgo-pug-setup#350]
first map chooser vote working but bo2 vote and bo3 vote not working, server changing maps random or sometimes is stucked on last scoreboard.

**Comment by asm00009** [comment]
I'm not sure but its maybe mapchooser and nexmap misconfiguration. Since nextmap always choose a map from mapcycle in beginning of match(map). And mapchooser have an option to choose a random map in end of map. 
[https://wiki.alliedmods.net/Map_Management_Plugins_(SourceMod)](url)

Btw I fixed my nextmap thing by putting a sm_nextmap "" in custom cfg file. Since it choose at the beginning of the match

**Comment by splewis** [comment]
> first map chooser vote working but bo2 vote and bo3 vote not working, server changing maps random or sometimes is stucked on last scoreboard.

There is no b2 or bo3 vote in pugsetup, so I don't know what you're referring to.

If you believe there's a pugsetup bug, please file clear steps to reproduce (plugin version, and what you tried to do).
