### ISSUE TITLE
Disable Postgame Reset or Score resetting

### ISSUE THREAD

**Issue by Vin-Zar** [splewis/csgo-pug-setup#375]
I have been trying to disable the automatic reset at the end of the game.
I tried using **{ _sm_pugsetup_postgame_cfg_ "" }** to disable the reset, however when testing it out on a PUG with friends, it still resets instantly at the end of the game and the scoreboard also resets. Is there anyway to disable the auto reset at the end in the latest build?

**Comment by splewis** [comment]
Pugsetup doesn't trigger any automatic reset, though the default configs (live.cfg) does set `mp_match_end_restart  1`.

AFAIK, setting that to 0 will lead to a map change instead of a restart, so I'm not sure that's really what you want. 

I'm not sure why you see "instantly" resetting behavior, you probably have some other cvar getting set. Maybe `mp_match_restart_delay  (defaulted to 30 in live.cfg)`?
