### ISSUE TITLE
Capt veto map issues

### ISSUE THREAD

**Issue by mumixam** [splewis/csgo-pug-setup#51]
Ive noticed a issue when using capt veto maps after all the maps are veto'd and the server changes to the last remaining map, its like the plugin was reset, you have to do .setup again

**Comment by encg** [comment]
I've run into the same issue. We end up doing .setup again and it forever loops. To fix this, we just set it to "current map" and have captains choose the same teams.

**Comment by splewis** [comment]
Thanks for the report, it should be fixed now by https://github.com/splewis/csgo-pug-setup/commit/7fcd96e00a4f2c54464704505c99b197ce4d6a1a

The issue was that the check done on client disconnect saw that 0 players were on the server, and called EndMatch, which terminated everything. (map changes cause all clients to disconnect then connect again).
